export const CHECK_LOCAL_STORAGE = "CHECK_LOCAL_STORAGE";
export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";
export const REMOVE_CITY = "REMOVE_CITY";